name: Extend_1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy=1.24.3
  - pip:
    - wandb==0.15.2
    - albumentations==1.3.0
    - opencv-python==4.7.0.72
    - imageio==2.26.1
    - torchsummary==1.5.1
    - pytorch-msssim==0.2.1 
    - Pillow==9.5.0
    - scikit-image==0.20.0
    - scipy==1.9.1
    - matplotlib==3.7.1
    - flopth==0.1.3